apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: palworld-admin-role
  namespace: palworld
rules:
- apiGroups: ["apps"]
  resources: ["statefulsets"]
  verbs: ["get", "patch", "update"]