[sssd]
services = nss, pam
config_file_version = 2
domains = the-hoffmanns.org

[domain/the-hoffmanns.org]
id_provider = ldap
auth_provider = ldap

ldap_uri = ldaps://ldap.the-hoffmanns.org:636
ldap_search_base = dc=the-hoffmanns,dc=org
ldap_user_search_base = ou=People,dc=the-hoffmanns,dc=org
ldap_group_search_base = ou=Groups,dc=the-hoffmanns,dc=org

ldap_tls_reqcert = demand

cache_credentials = True
enumerate = False