apiVersion: v1
kind: ConfigMap
metadata:
  name: coredns-custom
  namespace: kube-system
data:
  the-hoffmanns.server: |
    ldap.the-hoffmanns.org:53 {
        forward . 8.8.8.8
    }
    the-hoffmanns.org:53 {
        errors
        cache 30
        forward . 192.168.4.54
    }

