apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jellyfin-data
  namespace: jellyfin
spec:
  storageClassName: ""
  volumeName: jellyfin-data
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
