apiVersion: v1
kind: PersistentVolume
metadata:
  name: homebridge-data
spec:
  capacity:
    storage: 5Gi
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  nfs:
    server: grist.the-hoffmanns.org
    path: /apps/homebridge
