apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: homebridge-data
  namespace: homebridge
spec:
  storageClassName: ""
  volumeName: homebridge-data
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
